### ISSUE TITLE
IMU issues

### ISSUE THREAD

**Issue by nonlinear1** [CVLAB-Unibo/Slam-Dunk-Android#3]
Your code is very good when it is run on android phone. I really like it. when I run it with imu of android phone. I can run it. but I cann't map correctly. the map is wrong. In your code. I was confusing with the follwing code on ApplicationManager.java line 593:

EigenVector3F translationTemp = cameraPose2.getTranslation().toFloat();
translationTemp.setY(-translationTemp.getY());
translationTemp.setZ(-translationTemp.getZ());
KalmanGlobal.handleData(DataIMU.createPositionData(translationTemp));

Are these codes  for the transformation from camera to imu or the opposite?

**Comment by AlessioTonioni** [comment]
Duplicated
